import { v2 as cloudinary } from 'cloudinary';
import { log } from 'console';
import fs from 'fs';



    
    cloudinary.config({ 
        cloud_name: process.env.CLOUDINARY_CLOUD_NAME , 
        api_key: process.env.CLOUDINARY_API_KEY, 
        api_secret: process.env.CLOUDINARY_API_SECRET // Click 'View API Keys' above to copy your API secret
    });


    const uploadOnCloudinary = async (localFilePath) => {
        try {
           if (!localFilePath) return null
           //upload the file to cloudinary
           const response = await cloudinary.uploader.upload(localFilePath, { 
            resource_type:"auto",
            })
            //file had been uploaded successfully
            console.log("File uploaded successfully",
            response.url);
            return response
    } catch (error) {
        fs.unlinkSync(localFilePath) //remove the locally saved temporary file as the upload operation failed
        console.error("Error uploading file", error);
    }
}


export { uploadOnCloudinary }